import 'package:pocketbase/pocketbase.dart';

/*
READ ME:
Please know that img that is represented in PocketBase (Backend) is not important.
It is only there to represent image the users will add. If you are making a view of any sorts,
you must use imageURL instead of img to showcase the item. In this model img is removed from the collection.
*/
/* 
LIST OF ALL DATA AND WHICH ONES WE USE
  "active": -- Only used in backend to determine whether item should be shown in app.           
  "category": -- It is used to filter it and add it correct views according to the category.            
  "collectionId": -- Possible to use it in controller. But not necessary.       
  "collectionName": -- Used in controller to get the data.       
  "created": -- No use as of now, autogenerated by PocketBase.
  "desc": -- Used in views
  "id": -- No use as of now, autogenerated by PocketBase.
  "img": -- Img itself is not used. But in backend we are required to use it to upload files.           
  "imgUrl": Used in views to display image. Image.network(imgUrl);
  "price": Used in views
  "title": Used in views 
  "updated": -- No use as of now, autogenerated by PocketBase.
 */

class MenuItem {
  bool active;
  String title;
  String desc;
  String category;
  String imgUrl;
  double price;

  MenuItem(this.active, this.title, this.desc, this.price, this.category,
      this.imgUrl);

  static MenuItem fromModel(RecordModel model) {
    bool active = model.getBoolValue('active');
    String title = model.getStringValue('title');
    String desc = model.getStringValue('desc');
    String imgUrl = model.getStringValue('imgUrl');
    String category = model.getStringValue('category');
    double price = model.getDoubleValue('price');

    return MenuItem(active, title, desc, price, category, imgUrl);
  }
}
